version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: fastapi-backend
    ports:
      - "5000:5000"
    networks:
      - backend_network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: django-frontend
    ports:
      - "8000:8000"
    networks:
      - backend_network
    depends_on:
      - backend

networks:
  backend_network:
    driver: bridge
