name: CI

# =============================
# Github action for pushing to main branch
# ==============================
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test, Mypy & Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.9"


      #============================================
      #             Backend Tests
      #============================================

      - name: update pip
        run: |
          uv run python -m ensurepip --upgrade
          uv run python -m pip install --upgrade pip
          uv run pip install --upgrade setuptools wheel
        working-directory: backend

      - name: Install the project
        run:  |
            uv sync --group cpu --no-build-isolation
        working-directory: backend

      - name: Install dependencies
        run: |
          uv run pip install --no-build-isolation 'git+https://github.com/facebookresearch/detectron2.git'
        working-directory: backend

      - name: Run tests Backend
        working-directory: backend
        run: |
          uv run --no-sync pytest -m "not manual"
          uv run --no-sync mypy
          uv run --no-sync ruff check . 
          uv run --no-sync pyright


      #============================================
      #             Frontend Tests
      #============================================
      - name: Install the project
        run:  uv sync --no-build-isolation
        working-directory: frontend

      - name: Run tests frontend
        working-directory: frontend
        run: |
          uv run --no-sync pytest -m "not manual"
          uv run --no-sync mypy
          uv run --no-sync ruff check . 
          uv run --no-sync pyright
