name: CI

# =============================
# Github action for pushing to main branch
# ==============================
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test, Mypy & Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.9"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      #============================================
      #             Backend Tests
      #============================================
      - name: Run tests Backend
        working-directory: backend
        run: |
          uv run pytest

      # Run mypy type checks
      - name: Run mypy backend
        working-directory: backend
        run: |
          uv run mypy

      # Run ruff linting
      - name: Run ruff backend
        working-directory: backend
        run: |
          uv run ruff check . 

      #============================================
      #             Backend Tests
      #============================================
      - name: Run tests Fronetend
        working-directory: frontend
        run: |
          uv run pytest

      # Run mypy type checks
      - name: Run mypy Frontend
        working-directory: frontend
        run: |
          uv run mypy

      # Run ruff linting
      - name: Run ruff Frontend
        working-directory: frontend
        run: |
          uv run ruff check . 
